# docker-compose.yml
version: "3.8"
services:
  gmail:
    image: mcp/gmail
    command: auth
    ports:
      - "3000:3000"
      - "5680:5680"
    environment:
      GMAIL_OAUTH_PATH: /gcp-oauth.keys.json
      GMAIL_CREDENTIALS_PATH: /gmail-server/credentials.json
    volumes:
      - /path/to/gcp-oauth.keys.json:/gcp-oauth.keys.json
      - mcp-gmail:/gmail-server

volumes:
  mcp-gmail:
